markdown: kramdown
theme: minima
plugins: []

permalink: pretty

url: "https://cesarepeli.com"
baseurl: ""

exclude:
  - .nojekyll
  - README.md
  - node_modules
  - Gemfile
  - Gemfile.lock

collections:
  gallery:
    output: true

kramdown:
  input: GFM
  parse_block_html: true
