markdown: kramdown
theme: minima
plugins: []

permalink: pretty

exclude:
  - .nojekyll
  - README.md
  - node_modules
  - Gemfile
  - Gemfile.lock

# Se stai usando un repo "project site"
baseurl: "/Math_Physics_Logic"
url: "https://cesarepeli.com"
